apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend
  namespace: doctor-dev
  labels:
    project: doctor-appointment
    tier: frontend
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      project: doctor-appointment
      tier: frontend
      env: dev
  template:
    metadata:
      labels:
        project: doctor-appointment
        tier: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: vidya07422/doctor-frontend:v1
        # envFrom:
        # - configMapRef:
        #     name: doctor-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: doctor-dev
  labels:
    project: doctor-appointment
    tier: frontend
    env: dev
spec:
  type: LoadBalancer
  selector:
    project: doctor-appointment
    tier: frontend
    env: dev
  ports:
  - protocol: TCP
    port: 80 # service port which you want to expose
    targetPort: 80 # container port  