apiVersion: v1
kind: ConfigMap
metadata: 
  name: doctor-db-mysql
  namespace: doctor-dev
  labels:
    project: doctor-appointment
    tier: database
    env: dev
data:
  MYSQL_ROOT_PASSWORD: DoctorApp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-db-mysql
  namespace: doctor-dev
  labels:
    project: doctor-appointment
    tier: database
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: doctor-appointment
      tier: database
      env: dev
  template:
    metadata:
      labels:
        project: doctor-appointment
        tier: database
        env: dev
    spec:
      containers:
      - name: database
        image: vidya07422/doctor-mysql:v1
        envFrom:
        - configMapRef:
            name: doctor-db-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: doctor-dev
  labels:
    project: doctor-appointment
    tier: database
    env: dev
spec:
  selector:
    project: doctor-appointment
    tier: database
    env: dev
  ports:
  - protocol: TCP
    port: 3306 # service port which you want to expose
    targetPort: 3306 # container port  